### ISSUE TITLE
"イシューベースの開発"レビュー依頼

### ISSUE THREAD

**Issue by fy622** [fy622/portfolio#14]
### 実装予定の機能
- [ ] 会員登録
- [ ] ログイン
- [ ] ルート生成
- [ ] ルート生成履歴一覧

### 必要なページ
- [ ] 会員登録ページ
- [ ] ログインページ
- [ ] トップページ
- [ ] ログイン後トップページ
- [ ] ルート生成結果ページ
- [ ] ルート詳細ページ
- [ ] マイページ

**Comment by kenchasonakai** [comment]
カリキュラムを再度確認して実装予定の機能やGitHubProjectのURLを記入したうえで再度ご提出をお願いいたします
https://school.runteq.jp/v3/curriculums/graduate_examination/chapters/4

**Comment by fy622** [comment]
ご確認ありがとうございます！
また、確認不足でお手数おかけしまして大変失礼いたしました。

実装予定機能、必要なページを追記させていただきましたので、ご確認よろしくお願いいたします。

**Comment by kashiwagi-rena** [comment]
ご対応いただきありがとうございます。
以下、コメントです。

---

ストーリーポイント5の「ルート生成結果#11」の実装内容が多いと感じました。
APIに関してのものとRailsに実装するものに分けていただき、ストーリーポイント3にしていただくと、より進歩を感じなから実装をすることが可能と認識いたしましたので、ご確認・ご対応の方をよろしくお願いいたします。

**Comment by fy622** [comment]
ご確認いただきましてありがとうございます。

ご指摘の通りイシュー#11について、分割いたしました。
改めまして、ご確認よろしくお願いいたします。

**Comment by tarakish** [comment]
Projectsにアクセスしましたが、GitHub Projectが紐づいていないようです。カリキュラムをご確認の上、上記が確認できる状態でご提出をお願いいたします。
![スクリーンショット 2024-07-25 19 08 31](https://github.com/user-attachments/assets/1ce87fa4-3c01-4959-82ee-1746c7284046)

**Comment by fy622** [comment]
ご確認ありがとうございます！

紐づけましたので、改めてご確認よろしくお願いいたします。
